kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: timberline-test
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    # Log Ingestor API (9xxx for kind/k8s)
    - containerPort: 30200
      hostPort: 9200
      protocol: TCP
    # Log Ingestor Metrics
    - containerPort: 30201
      hostPort: 9201
      protocol: TCP
    # Milvus Database
    - containerPort: 30530
      hostPort: 9530
      protocol: TCP
    # Milvus Metrics
    - containerPort: 30091
      hostPort: 9091
      protocol: TCP
    # Embedding Service
    - containerPort: 30100
      hostPort: 9100
      protocol: TCP
    # Chat Service
    - containerPort: 30101
      hostPort: 9101
      protocol: TCP
    # MinIO Console
    - containerPort: 30901
      hostPort: 9901
      protocol: TCP
    # MinIO API
    - containerPort: 30900
      hostPort: 9900
      protocol: TCP
    # Attu (Milvus UI)
    - containerPort: 30300
      hostPort: 9300
      protocol: TCP
    # Fluent Bit Metrics
    - containerPort: 30020
      hostPort: 9020
      protocol: TCP
  - role: worker
    labels:
      worker-type: compute