kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: timberline-test
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    # Log Ingestor API
    - containerPort: 30080
      hostPort: 8080
      protocol: TCP
    # Log Ingestor Metrics
    - containerPort: 30092
      hostPort: 9092
      protocol: TCP
    # Milvus Database
    - containerPort: 30530
      hostPort: 19530
      protocol: TCP
    # Milvus Metrics
    - containerPort: 30091
      hostPort: 9091
      protocol: TCP
    # Embedding Service
    - containerPort: 30800
      hostPort: 8000
      protocol: TCP
    # Chat Service
    - containerPort: 30801
      hostPort: 8001
      protocol: TCP
    # MinIO Console
    - containerPort: 30901
      hostPort: 9001
      protocol: TCP
    # MinIO API
    - containerPort: 30900
      hostPort: 9000
      protocol: TCP
    # Attu (Milvus UI)
    - containerPort: 30300
      hostPort: 3000
      protocol: TCP
    # Fluent Bit Metrics
    - containerPort: 30090
      hostPort: 9090
      protocol: TCP
  - role: worker
    labels:
      worker-type: compute