apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-embedding
  namespace: timberline
  labels:
    app: llama-cpp-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp-embedding
  template:
    metadata:
      labels:
        app: llama-cpp-embedding
    spec:
      initContainers:
      - name: download-model
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          if [ ! -f /models/nomic-embed-text-v1.5.f16.gguf ]; then
            echo "Downloading embedding model..."
            wget -O /models/nomic-embed-text-v1.5.f16.gguf \
              https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.f16.gguf
          else
            echo "Model already exists"
          fi
        volumeMounts:
        - name: models
          mountPath: /models
      containers:
      - name: llama-cpp
        image: ghcr.io/ggml-org/llama.cpp:server
        command:
        - /app/llama-server
        args:
        - -m
        - /models/nomic-embed-text-v1.5.f16.gguf
        - --embeddings
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        - --threads
        - "8"
        - --ctx-size
        - "2048"
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: models
          mountPath: /models
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: models
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-embedding
  namespace: timberline
  labels:
    app: llama-cpp-embedding
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    nodePort: 30800
  selector:
    app: llama-cpp-embedding
  type: NodePort