apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: timberline
  labels:
    app: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.6.2
        command:
        - milvus
        - run
        - standalone
        env:
        - name: MINIO_REGION
          value: us-east-1
        - name: ETCD_ENDPOINTS
          value: etcd:2379
        - name: MINIO_ADDRESS
          value: minio:9000
        ports:
        - containerPort: 19530
          name: grpc
        - containerPort: 9091
          name: metrics
        volumeMounts:
        - name: milvus-data
          mountPath: /var/lib/milvus
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: milvus-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: timberline
  labels:
    app: milvus
spec:
  ports:
  - port: 19530
    targetPort: 19530
    name: grpc
    nodePort: 30530
  - port: 9091
    targetPort: 9091
    name: metrics
    nodePort: 30091
  selector:
    app: milvus
  type: NodePort