linters:
  disable:
    - typecheck  # Disable typecheck as it's not working with our Go version
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - errcheck
    - gosimple
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/timberline/log-ingestor

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  exclude-rules: []

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true