"""Add analysis_jobs table

Revision ID: f1b3296e1dc3
Revises: 5293afbbe3f1
Create Date: 2025-10-03 18:04:40.294274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b3296e1dc3'
down_revision: Union[str, Sequence[str], None] = '5293afbbe3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('time_range_hours', sa.Integer(), nullable=False),
    sa.Column('min_cluster_size', sa.Integer(), nullable=False),
    sa.Column('cluster_count', sa.Integer(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('clusters', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_created_at'), 'analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_created_at'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
