apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  namespace: timberline
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.4.8
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: MILVUS_URL
          value: "milvus:19530"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: timberline
  labels:
    app: attu
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    nodePort: 30300
  selector:
    app: attu
  type: NodePort