name: Build and Push Log Ingestor

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic version tags (e.g., v1.0.0)
    branches:
      - main      # Also build on main branch pushes
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/log-ingestor

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git describe

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'log-ingestor/go.mod'

      - name: Run tests
        working-directory: log-ingestor
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version and image name
        id: meta
        run: |
          # Lowercase the repository owner for Docker registry compatibility
          IMAGE_NAME_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "image_name=${IMAGE_NAME_LOWER}/log-ingestor" >> $GITHUB_OUTPUT

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Use the tag name (strip refs/tags/ prefix)
            VERSION=${GITHUB_REF#refs/tags/}
          else
            # Use git describe for branch builds
            VERSION=$(git describe --tags --always --dirty)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Image: ${IMAGE_NAME_LOWER}/log-ingestor"
          echo "Version: $VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./log-ingestor
          file: ./log-ingestor/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}

      - name: Image digest
        run: echo "Image pushed with tags ${{ steps.meta.outputs.version }} and latest"
